---
- block:
    - name: "Install packages required."
      include_tasks: packages.yml
      tags: [pkgs]

    - name: "Enable and start daemons."
      include_tasks: services.yml
      tags: [services]

    - name: "Open Firewall ports."
      include_tasks: firewall.yml
      tags: [firewall]
  become: true 
