---

- name: "Enable Services." 
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ rh_daemons }}"

  #- name: "Start Services." 
  #  systemd:
  #    name: "{{ rh_daemons }}"
  #    state: started
